version: "3.7"

services:
  php:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - ./drupal:/var/www/html

  crond:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - ./drupal:/var/www/html

  nginx:
    volumes:
    - ./drupal:/var/www/html

#  webgrind:
#    volumes:
#    - codebase:/mnt/codebase

volumes:
  codebase:
